# Makefile para compilar generator.cpp

CXX = g++
CXXFLAGS = -std=c++17 -Wall -O2
TARGET = generator
SRC = generator.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)

